name: Desplegar a AWS S3
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Descargar archivos del repositorio
        uses: actions/checkout@v4

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 🌐 Instalar navegador Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🧪 Ejecutar pruebas
        run: npx ng test --browsers=ChromeHeadless --watch=false --no-watch --no-progress --browsers=ChromeHeadless
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable

      - name: 🔨 Compilar Angular para producción
        run: npx ng build --configuration=production

      - name: 🔑 Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 🚀 Subir archivos compilados al Bucket S3
        run: aws s3 sync ./dist/doryoku-kan/browser s3://doryoku-kan --delete